# Generated by Django 3.2.9 on 2021-11-22 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок теста')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='question_with_multiple_choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('answer1', models.CharField(max_length=100, verbose_name='Первый ответ')),
                ('answer2', models.CharField(max_length=100, verbose_name='Второй ответ')),
                ('answer3', models.CharField(max_length=100, verbose_name='Третий ответ')),
                ('answer4', models.CharField(max_length=100, verbose_name='Четвертый ответ')),
                ('correct_answer', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], verbose_name='Правильный ответ')),
                ('TestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='question_with_free_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('correct_answer', models.CharField(max_length=100, verbose_name='Правильный ответ')),
                ('TestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест')),
            ],
        ),
    ]
